import { setTimeout as sleep } from "node:timers/promises";

export type SourceFetchErrorKind = "http" | "empty-response" | "request-failed";

/** A sanitized failure generated by fetchText, safe to report in patrol diagnostics. */
export class SourceFetchError extends Error {
  readonly kind: SourceFetchErrorKind;
  readonly status: number | undefined;

  constructor(kind: SourceFetchErrorKind, status?: number) {
    super(kind === "http" ? `HTTP ${status}` : kind === "empty-response" ? "empty response" : "request failed or timed out");
    this.name = "SourceFetchError";
    this.kind = kind;
    this.status = status;
  }
}

export async function fetchText(url: string): Promise<string> {
  for (let attempt = 0; attempt < 3; attempt++) {
    try {
      const response = await fetch(url, {
        headers: { "User-Agent": "Mozilla/5.0 (compatible; HikaruAppearancePatrol/1.0)" },
        signal: AbortSignal.timeout(20_000),
      });
      if (!response.ok) {
        await response.body?.cancel();
        if ((response.status === 429 || response.status >= 500) && attempt < 2) {
          const retryAfter = Number(response.headers.get("retry-after"));
          await sleep(Math.min(10_000, Math.max(1000 * (attempt + 1), retryAfter * 1000 || 0)));
          continue;
        }
        throw new SourceFetchError("http", response.status);
      }
      const text = await response.text();
      if (!text.trim()) throw new SourceFetchError("empty-response");
      return text;
    } catch (error) {
      if (error instanceof SourceFetchError) throw error;
      if (attempt === 2) throw new SourceFetchError("request-failed");
      await sleep(1000 * (attempt + 1));
    }
  }
  throw new SourceFetchError("request-failed");
}
