import type { AppearanceSeries } from "../src/domain/appearance";

export const appearanceSeriesData = [
  { id: "gakuen-idolmaster", displayName: "学園アイドルマスター" },
  { id: "hikaroom", displayName: "飯田ヒカルのヒカROOM！" },
  { id: "kannahikaru", displayName: "カンナヒカル（仮）" },
  { id: "pikanono", displayName: "ぴかのの定理" },
  { id: "yuri-relation", displayName: "YuriRelation" },
  { id: "hagoromo6", displayName: "羽衣6" },
  { id: "one-and-only", displayName: "長月あおいのONE AND ONLY" },
  { id: "iida-hikaru-fanmeeting", displayName: "飯田ヒカル ファンミーティング" },
  { id: "llv-reading-series", displayName: "LLVリーディングシリーズ" },
  { id: "valentine-room", displayName: "ValentineRoom" },
  { id: "sashibana", displayName: "さしばな" },
  { id: "mlt", displayName: "MLT" },
  { id: "kiseki-series", displayName: "軌跡シリーズ" },
  { id: "gekirock", displayName: "GEKIROCK" },
  { id: "kotoneiro", displayName: "kotoneiro" },
  { id: "itagochi", displayName: "いたごち" },
  { id: "azupri", displayName: "あずぷり" },
  { id: "hitono-denwa", displayName: "ひとのでんわ" },
  { id: "futsuu-na-radio", displayName: "普通なラジオ" },
  { id: "anirave", displayName: "AniRAVE" },
  { id: "charamix", displayName: "キャラミクス" },
  { id: "stella-sora", displayName: "ステラソラ" },
  { id: "saesuzu", displayName: "さえすず" },
  { id: "onsen-festival", displayName: "音泉祭り" },
  { id: "usui-frontier", displayName: "うすいフロンティア" },
  { id: "tricolor-color", displayName: "礒部花凜・土屋李央・林鼓子 トリコロールカラー" },
  { id: "hanaiwa-world", displayName: "花岩香奈のはないわーるど" },
  { id: "grand-blue", displayName: "ぐらんぶる" },
  { id: "ascendance-of-a-bookworm", displayName: "本好きの下剋上" },
  { id: "iyapan", displayName: "嫌な顔されながらおパンツ見せてもらいたい" },
  { id: "ichijoma", displayName: "一畳間まんきつ暮らし！" },
] as const satisfies readonly AppearanceSeries[];
