import type { AppearanceImportItem } from "../../src/domain/appearance";
import { publishedAt, publishedOn, single, singleDate, singleUnknown } from "./helpers";

const agencyProfileUrl = "https://www.raccoon-dog.co.jp/talent/r18-iida.html";

export const voiceAppearances = [
  single({
    id: "grand-blue-season-2",
    startsAt: "2025-09-09T00:30:00+09:00",
    title: "TVアニメ『ぐらんぶる』Season 2（声の出演）",
    seriesId: "grand-blue",
    category: "テレビ",
    sourceUrl: agencyProfileUrl,
    sourceName: "official:raccoon-dog",
    sourceItemId: "profile:tv:grand-blue-season-2",
  }),
  single({
    id: "booklove-adopted-daughter-season",
    startsAt: "2026-04-11T17:30:00+09:00",
    title: "TVアニメ『本好きの下剋上 領主の養女』シーズン出演",
    seriesId: "ascendance-of-a-bookworm",
    category: "テレビ",
    sourceUrl: agencyProfileUrl,
    sourceName: "official:raccoon-dog",
    sourceItemId: "profile:tv:booklove-adopted-daughter",
  }),
  single({
    id: "iyapan-r",
    startsAt: "2026-05-07T22:00:00+09:00",
    title: "Webアニメ『嫌な顔されながらおパンツ見せてもらいたいR』（声の出演）",
    seriesId: "iyapan",
    category: "配信",
    sourceUrl: agencyProfileUrl,
    sourceName: "official:raccoon-dog",
    sourceItemId: "profile:web:iyapan-r",
  }),
  single({
    id: "ichijoma",
    startsAt: "2026-05-10T02:00:00+09:00",
    title: "TVアニメ『一畳間まんきつ暮らし！』（声の出演）",
    seriesId: "ichijoma",
    category: "テレビ",
    sourceUrl: agencyProfileUrl,
    sourceName: "official:raccoon-dog",
    sourceItemId: "profile:tv:ichijoma",
  }),
  singleDate({
    id: "oshigoto-neiro-encore-biyoushi",
    startsOn: "2025-11-10",
    title: "ASMR『おしごとねいろ アンコール ～美容師編～』",
    seriesId: "kotoneiro",
    category: "音声作品",
    sourceUrl: "https://www.youtube.com/live/fWexqZR_35I",
    publication: publishedOn("2025-11-10"),
    sourceName: "official:youtube",
    sourceItemId: "youtube:live:fWexqZR_35I",
  }),
  singleDate({
    id: "toushindai-no-kanojo-school-stay",
    startsOn: "2026-08-13",
    title: "ASMR『等身大の彼女～二人きりの学校お泊り～』（織井澄玲 役）",
    seriesId: null,
    category: "音声作品",
    sourceUrl: "https://prtimes.jp/main/html/rd/p/000000026.000020837.html",
    publication: publishedAt("2026-08-12T00:00:00+09:00"),
    sourceName: "official:pr-times",
    sourceItemId: "prtimes:000000026.000020837",
  }),
  singleUnknown({
    id: "sugar-lies-asmr-series",
    title: "『Sugar Lies』ASMRボイスドラマシリーズ（雪平明星 役）",
    seriesId: "sugar-lies",
    category: "音声作品",
    sourceUrl: "https://sugarlies.kogado.com/",
    publication: publishedOn("2026-09-18"),
    sourceName: "official:kogado",
    sourceItemId: "kogado:sugarlies:asmr",
  }),
] satisfies readonly AppearanceImportItem[];
